"""Removed weight column

Revision ID: 959634645538
Revises: 
Create Date: 2025-02-19 09:26:16.063675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959634645538'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
